import { SuperAgentRequest } from 'superagent'
import { stubFor } from '../wiremock'

const stubChallengesReferenceData = (): SuperAgentRequest =>
  stubFor({
    request: {
      method: 'GET',
      urlPath: '/support-additional-needs-api/reference-data/CHALLENGE',
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        referenceDataList: [
          {
            code: 'READING',
            description: 'Reading',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 1,
            active: true,
          },
          {
            code: 'SPELLING',
            description: 'Spelling',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 2,
            active: true,
          },
          {
            code: 'WRITING',
            description: 'Writing',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 3,
            active: true,
          },
          {
            code: 'ALPHABET_ORDERING',
            description: 'Alphabet ordering',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 4,
            active: true,
          },
          {
            code: 'READING_COMPREHENSION',
            description: 'Reading comprehension',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 5,
            active: true,
          },
          {
            code: 'READING_VISUAL_DISCRIMINATION',
            description: 'Reading (visual discrimination)',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 6,
            active: true,
          },
          {
            code: 'TRACKING',
            description: 'Tracking',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 7,
            active: true,
          },
          {
            code: 'LANGUAGE_DECODING',
            description: 'Language decoding',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 8,
            active: true,
          },
          {
            code: 'SPEED_OF_CALCULATION',
            description: 'Speed of calculation',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 1,
            active: true,
          },
          {
            code: 'ARITHMETIC',
            description: 'Arithmetic',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 2,
            active: true,
          },
          {
            code: 'ESTIMATION',
            description: 'Estimation',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 3,
            active: true,
          },
          {
            code: 'MATHS_LITERACY',
            description: 'Maths literacy',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 4,
            active: true,
          },
          {
            code: 'MATHS_CONFIDENCE',
            description: 'Maths confidence',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 5,
            active: true,
          },
          {
            code: 'FRACTIONS_PERCENTAGES',
            description: 'Fractions and percentages',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 6,
            active: true,
          },
          {
            code: 'WORD_BASED_PROBLEMS',
            description: 'Word-based problems',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 7,
            active: true,
          },
          {
            code: 'MONEY_MANAGEMENT',
            description: 'Money management',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 8,
            active: true,
          },
          {
            code: 'NUMBER_RECALL',
            description: 'Number recall',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 9,
            active: true,
          },
          {
            code: 'NUMBER_SEQUENCING',
            description: 'Number sequencing',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 10,
            active: true,
          },
          {
            code: 'FOCUSING',
            description: 'Focusing',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 1,
            active: true,
          },
          {
            code: 'TIDINESS',
            description: 'Tidiness',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 2,
            active: true,
          },
          {
            code: 'FINISHING_TASKS',
            description: 'Finishing tasks',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 3,
            active: true,
          },
          {
            code: 'PROBLEM_SOLVING',
            description: 'Problem solving',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 4,
            active: true,
          },
          {
            code: 'TASK_INITIATION',
            description: 'Task initiation',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 5,
            active: true,
          },
          {
            code: 'TIME_ALLOCATION',
            description: 'Time allocation/prioritisation',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 6,
            active: true,
          },
          {
            code: 'SELF_ORGANISED',
            description: 'Self-organised (routine)',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 7,
            active: true,
          },
          {
            code: 'FORWARD_PLANNING',
            description: 'Forward planning',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 8,
            active: true,
          },
          {
            code: 'ATTENTION_TO_DETAIL',
            description: 'Attention to detail',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 9,
            active: true,
          },
          {
            code: 'TASK_SWITCHING',
            description: 'Task switching',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 10,
            active: true,
          },
          {
            code: 'TURN_TAKING',
            description: 'Turn-taking',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 1,
            active: true,
          },
          {
            code: 'LANGUAGE_FLUENCY',
            description: 'Language fluency',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 2,
            active: true,
          },
          {
            code: 'SOCIAL_ADAPTABILITY',
            description: 'Social adaptability',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 3,
            active: true,
          },
          {
            code: 'COMMUNICATION',
            description: 'Communication',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 4,
            active: true,
          },
          {
            code: 'EXTROVERSION_INTROVERSION',
            description: 'Extroversion/Introversion',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 5,
            active: true,
          },
          {
            code: 'SOCIAL_NUANCES',
            description: 'Social nuances',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 6,
            active: true,
          },
          {
            code: 'SPEAKING',
            description: 'Speaking',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 7,
            active: true,
          },
          {
            code: 'WORD_FINDING',
            description: 'Word finding',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 8,
            active: true,
          },
          {
            code: 'ACTIVE_LISTENING',
            description: 'Active listening',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 9,
            active: true,
          },
          {
            code: 'NON_VERBAL_COMMUNICATION',
            description: 'Non-verbal communication',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 10,
            active: true,
          },
          {
            code: 'PEOPLE_PERSON',
            description: 'People person',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 11,
            active: true,
          },
          {
            code: 'RESTFULNESS',
            description: 'Restfulness',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 1,
            active: true,
          },
          {
            code: 'READING_EMOTIONS',
            description: 'Reading emotions',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 2,
            active: true,
          },
          {
            code: 'EMPATHY',
            description: 'Empathy',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 3,
            active: true,
          },
          {
            code: 'IMPULSE_CONTROL',
            description: 'Impulse control',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 4,
            active: true,
          },
          {
            code: 'EMOTIONAL_CONTROL',
            description: 'Emotional control',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 5,
            active: true,
          },
          {
            code: 'MANAGING_CHANGE',
            description: 'Managing change (adaptability)',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 6,
            active: true,
          },
          {
            code: 'CONFIDENCE',
            description: 'Confidence',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 7,
            active: true,
          },
          {
            code: 'CALM',
            description: 'Calm',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 8,
            active: true,
          },
          {
            code: 'HANDWRITING',
            description: 'Handwriting',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 1,
            active: true,
          },
          {
            code: 'BALANCE',
            description: 'Balance',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 2,
            active: true,
          },
          {
            code: 'FINE_MOTOR_SKILLS',
            description: 'Fine motor skills',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 3,
            active: true,
          },
          {
            code: 'LEARNING_NEW_SKILLS',
            description: 'Learning new skills',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 4,
            active: true,
          },
          {
            code: 'SPORTING_BALL_SKILLS',
            description: 'Sporting ball skills',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 5,
            active: true,
          },
          {
            code: 'DUAL_TASKING',
            description: 'Dual tasking',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 6,
            active: true,
          },
          {
            code: 'FOLDING_PACKING_SORTING',
            description: 'Folding, packing, and sorting',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 7,
            active: true,
          },
          {
            code: 'STAMINA',
            description: 'Stamina',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 8,
            active: true,
          },
          {
            code: 'GRASP',
            description: 'Grasp',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 9,
            active: true,
          },
          {
            code: 'SPATIAL_AWARENESS',
            description: 'Spatial awareness',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 10,
            active: true,
          },
          {
            code: 'AUDITORY_DISCRIMINATION',
            description: 'Auditory Discrimination',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 1,
            active: true,
          },
          {
            code: 'CREATIVITY',
            description: 'Creativity',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 2,
            active: true,
          },
          {
            code: 'LISTENING',
            description: 'Listening',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 3,
            active: true,
          },
          {
            code: 'SENSORY_PROCESSING',
            description: 'Sensory processing',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 4,
            active: true,
          },
          {
            code: 'VISUAL_SKILLS',
            description: 'Visual skills',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 5,
            active: true,
          },
          {
            code: 'VISUAL_SPATIAL_SKILLS',
            description: 'Visual-Spatial Skills',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 6,
            active: true,
          },
        ],
      },
    },
  })

const stubStrengthsReferenceData = (): SuperAgentRequest =>
  stubFor({
    request: {
      method: 'GET',
      urlPath: '/support-additional-needs-api/reference-data/STRENGTH',
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        referenceDataList: [
          {
            code: 'READING',
            description: 'Reading',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 1,
            active: true,
          },
          {
            code: 'SPELLING',
            description: 'Spelling',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 2,
            active: true,
          },
          {
            code: 'WRITING',
            description: 'Writing',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 3,
            active: true,
          },
          {
            code: 'ALPHABET_ORDERING',
            description: 'Alphabet ordering',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 4,
            active: true,
          },
          {
            code: 'READING_COMPREHENSION',
            description: 'Reading comprehension',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 5,
            active: true,
          },
          {
            code: 'READING_VISUAL_DISCRIMINATION',
            description: 'Reading (visual discrimination)',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 6,
            active: true,
          },
          {
            code: 'TRACKING',
            description: 'Tracking',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 7,
            active: true,
          },
          {
            code: 'LANGUAGE_DECODING',
            description: 'Language decoding',
            categoryCode: 'LITERACY_SKILLS',
            categoryDescription: 'Literacy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 8,
            active: true,
          },
          {
            code: 'SPEED_OF_CALCULATION',
            description: 'Speed of calculation',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 1,
            active: true,
          },
          {
            code: 'ARITHMETIC',
            description: 'Arithmetic',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 2,
            active: true,
          },
          {
            code: 'ESTIMATION',
            description: 'Estimation',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 3,
            active: true,
          },
          {
            code: 'MATHS_LITERACY',
            description: 'Maths literacy',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 4,
            active: true,
          },
          {
            code: 'MATHS_CONFIDENCE',
            description: 'Maths confidence',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 5,
            active: true,
          },
          {
            code: 'FRACTIONS_PERCENTAGES',
            description: 'Fractions and percentages',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 6,
            active: true,
          },
          {
            code: 'WORD_BASED_PROBLEMS',
            description: 'Word-based problems',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 7,
            active: true,
          },
          {
            code: 'MONEY_MANAGEMENT',
            description: 'Money management',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 8,
            active: true,
          },
          {
            code: 'NUMBER_RECALL',
            description: 'Number recall',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 9,
            active: true,
          },
          {
            code: 'NUMBER_SEQUENCING',
            description: 'Number sequencing',
            categoryCode: 'NUMERACY_SKILLS',
            categoryDescription: 'Numeracy Skills',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 10,
            active: true,
          },
          {
            code: 'FOCUSING',
            description: 'Focusing',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 1,
            active: true,
          },
          {
            code: 'TIDINESS',
            description: 'Tidiness',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 2,
            active: true,
          },
          {
            code: 'FINISHING_TASKS',
            description: 'Finishing tasks',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 3,
            active: true,
          },
          {
            code: 'PROBLEM_SOLVING',
            description: 'Problem solving',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 4,
            active: true,
          },
          {
            code: 'TASK_INITIATION',
            description: 'Task initiation',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 5,
            active: true,
          },
          {
            code: 'TIME_ALLOCATION',
            description: 'Time allocation/prioritisation',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 6,
            active: true,
          },
          {
            code: 'SELF_ORGANISED',
            description: 'Self-organised (routine)',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 7,
            active: true,
          },
          {
            code: 'FORWARD_PLANNING',
            description: 'Forward planning',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 8,
            active: true,
          },
          {
            code: 'ATTENTION_TO_DETAIL',
            description: 'Attention to detail',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 9,
            active: true,
          },
          {
            code: 'TASK_SWITCHING',
            description: 'Task switching',
            categoryCode: 'ATTENTION_ORGANISING_TIME',
            categoryDescription: 'Attention, Organising & Time Management',
            areaCode: 'COGNITION_LEARNING',
            areaDescription: 'Cognition & Learning',
            listSequence: 10,
            active: true,
          },
          {
            code: 'TURN_TAKING',
            description: 'Turn-taking',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 1,
            active: true,
          },
          {
            code: 'LANGUAGE_FLUENCY',
            description: 'Language fluency',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 2,
            active: true,
          },
          {
            code: 'SOCIAL_ADAPTABILITY',
            description: 'Social adaptability',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 3,
            active: true,
          },
          {
            code: 'COMMUNICATION',
            description: 'Communication',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 4,
            active: true,
          },
          {
            code: 'EXTROVERSION_INTROVERSION',
            description: 'Extroversion/Introversion',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 5,
            active: true,
          },
          {
            code: 'SOCIAL_NUANCES',
            description: 'Social nuances',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 6,
            active: true,
          },
          {
            code: 'SPEAKING',
            description: 'Speaking',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 7,
            active: true,
          },
          {
            code: 'WORD_FINDING',
            description: 'Word finding',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 8,
            active: true,
          },
          {
            code: 'ACTIVE_LISTENING',
            description: 'Active listening',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 9,
            active: true,
          },
          {
            code: 'NON_VERBAL_COMMUNICATION',
            description: 'Non-verbal communication',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 10,
            active: true,
          },
          {
            code: 'PEOPLE_PERSON',
            description: 'People person',
            categoryCode: 'LANGUAGE_COMM_SKILLS',
            categoryDescription: 'Language & Communication skills',
            areaCode: 'COMMUNICATION_INTERACTION',
            areaDescription: 'Communication & Interaction',
            listSequence: 11,
            active: true,
          },
          {
            code: 'RESTFULNESS',
            description: 'Restfulness',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 1,
            active: true,
          },
          {
            code: 'READING_EMOTIONS',
            description: 'Reading emotions',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 2,
            active: true,
          },
          {
            code: 'EMPATHY',
            description: 'Empathy',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 3,
            active: true,
          },
          {
            code: 'IMPULSE_CONTROL',
            description: 'Impulse control',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 4,
            active: true,
          },
          {
            code: 'EMOTIONAL_CONTROL',
            description: 'Emotional control',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 5,
            active: true,
          },
          {
            code: 'MANAGING_CHANGE',
            description: 'Managing change (adaptability)',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 6,
            active: true,
          },
          {
            code: 'CONFIDENCE',
            description: 'Confidence',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 7,
            active: true,
          },
          {
            code: 'CALM',
            description: 'Calm',
            categoryCode: 'EMOTIONS_FEELINGS',
            categoryDescription: 'Emotions & feelings',
            areaCode: 'SOCIAL_EMOTIONAL_MENTAL',
            areaDescription: 'Social, Emotional & Mental Health',
            listSequence: 8,
            active: true,
          },
          {
            code: 'HANDWRITING',
            description: 'Handwriting',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 1,
            active: true,
          },
          {
            code: 'BALANCE',
            description: 'Balance',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 2,
            active: true,
          },
          {
            code: 'FINE_MOTOR_SKILLS',
            description: 'Fine motor skills',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 3,
            active: true,
          },
          {
            code: 'LEARNING_NEW_SKILLS',
            description: 'Learning new skills',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 4,
            active: true,
          },
          {
            code: 'SPORTING_BALL_SKILLS',
            description: 'Sporting ball skills',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 5,
            active: true,
          },
          {
            code: 'DUAL_TASKING',
            description: 'Dual tasking',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 6,
            active: true,
          },
          {
            code: 'FOLDING_PACKING_SORTING',
            description: 'Folding, packing, and sorting',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 7,
            active: true,
          },
          {
            code: 'STAMINA',
            description: 'Stamina',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 8,
            active: true,
          },
          {
            code: 'GRASP',
            description: 'Grasp',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 9,
            active: true,
          },
          {
            code: 'SPATIAL_AWARENESS',
            description: 'Spatial awareness',
            categoryCode: 'PHYSICAL_SKILLS',
            categoryDescription: 'Physical Skills & coordination',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 10,
            active: true,
          },
          {
            code: 'AUDITORY_DISCRIMINATION',
            description: 'Auditory Discrimination',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 1,
            active: true,
          },
          {
            code: 'CREATIVITY',
            description: 'Creativity',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 2,
            active: true,
          },
          {
            code: 'LISTENING',
            description: 'Listening',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 3,
            active: true,
          },
          {
            code: 'SENSORY_PROCESSING',
            description: 'Sensory processing',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 4,
            active: true,
          },
          {
            code: 'VISUAL_SKILLS',
            description: 'Visual skills',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 5,
            active: true,
          },
          {
            code: 'VISUAL_SPATIAL_SKILLS',
            description: 'Visual-Spatial Skills',
            categoryCode: 'SENSORY',
            categoryDescription: 'Sensory',
            areaCode: 'PHYSICAL_SENSORY',
            areaDescription: 'Physical & Sensory',
            listSequence: 6,
            active: true,
          },
        ],
      },
    },
  })

const stubConditionsReferenceData = (): SuperAgentRequest =>
  stubFor({
    request: {
      method: 'GET',
      urlPath: '/support-additional-needs-api/reference-data/CONDITION',
    },
    response: {
      status: 200,
      headers: { 'Content-Type': 'application/json;charset=UTF-8' },
      jsonBody: {
        referenceDataList: [
          {
            code: 'DLD_HEAR',
            description: 'Hearing Impairment',
            categoryCode: 'COMMUNICATION_IMPAIRMENT',
            categoryDescription: 'Hearing, speech, language and / or communication impairment',
            areaCode: null,
            areaDescription: null,
            listSequence: 1,
            active: true,
          },
          {
            code: 'ASC',
            description: 'Autism Spectrum Condition',
            categoryCode: 'AUTISM',
            categoryDescription: 'Autism Spectrum Disorder',
            areaCode: null,
            areaDescription: null,
            listSequence: 1,
            active: true,
          },
          {
            code: 'MENTAL_HEALTH',
            description: 'Mental Health',
            categoryCode: 'MENTAL_HEALTH',
            categoryDescription: 'Mental Health',
            areaCode: null,
            areaDescription: null,
            listSequence: 1,
            active: true,
          },
          {
            code: 'VISUAL_IMPAIR',
            description: 'Visual Impairment',
            categoryCode: 'VISUAL_IMPAIRMENT',
            categoryDescription: 'Visual Impairment',
            areaCode: null,
            areaDescription: null,
            listSequence: 1,
            active: true,
          },
          {
            code: 'LD_DOWN',
            description: "Down's Syndrome",
            categoryCode: 'LEARNING_DISABILITY',
            categoryDescription: 'Learning Disability',
            areaCode: null,
            areaDescription: null,
            listSequence: 1,
            active: true,
          },
          {
            code: 'ADHD',
            description: 'Attention Deficit Hyperactivity Disorder (ADHD / ADD)',
            categoryCode: 'LEARNING_DIFFICULTY',
            categoryDescription: 'Learning Difficulty',
            areaCode: null,
            areaDescription: null,
            listSequence: 1,
            active: true,
          },
          {
            code: 'DYSLEXIA',
            description: 'Dyslexia',
            categoryCode: 'LEARNING_DIFFICULTY',
            categoryDescription: 'Learning Difficulty',
            areaCode: null,
            areaDescription: null,
            listSequence: 2,
            active: true,
          },
          {
            code: 'LD_OTHER',
            description: 'Other learning disability',
            categoryCode: 'LEARNING_DISABILITY',
            categoryDescription: 'Learning Disability',
            areaCode: null,
            areaDescription: null,
            listSequence: 2,
            active: true,
          },
          {
            code: 'DLD_LANG',
            description: 'Developmental Language Disorder',
            categoryCode: 'COMMUNICATION_IMPAIRMENT',
            categoryDescription: 'Hearing, speech, language and / or communication impairment',
            areaCode: null,
            areaDescription: null,
            listSequence: 2,
            active: true,
          },
          {
            code: 'DLD_OTHER',
            description: 'Other Language / speech / communication disorder',
            categoryCode: 'COMMUNICATION_IMPAIRMENT',
            categoryDescription: 'Hearing, speech, language and / or communication impairment',
            areaCode: null,
            areaDescription: null,
            listSequence: 3,
            active: true,
          },
          {
            code: 'DYSPRAXIA',
            description: 'Dyspraxia / Developmental Coordination Disorder',
            categoryCode: 'LEARNING_DIFFICULTY',
            categoryDescription: 'Learning Difficulty',
            areaCode: null,
            areaDescription: null,
            listSequence: 3,
            active: true,
          },
          {
            code: 'DYSCALCULIA',
            description: 'Dyscalculia',
            categoryCode: 'LEARNING_DIFFICULTY',
            categoryDescription: 'Learning Difficulty',
            areaCode: null,
            areaDescription: null,
            listSequence: 4,
            active: true,
          },
          {
            code: 'LEARN_DIFF_OTHER',
            description: 'Other',
            categoryCode: 'LEARNING_DIFFICULTY',
            categoryDescription: 'Learning Difficulty',
            areaCode: null,
            areaDescription: null,
            listSequence: 5,
            active: true,
          },
          {
            code: 'PHYSICAL_OTHER',
            description: 'Conditions restricting mobility / dexterity',
            categoryCode: 'MOBILITY',
            categoryDescription: 'Conditions restricting mobility / dexterity',
            areaCode: null,
            areaDescription: null,
            listSequence: 11,
            active: true,
          },
          {
            code: 'TOURETTES',
            description: "Tourette's Syndrome/Tic Disorder",
            categoryCode: 'NEUROLOGICAL_CONDITION',
            categoryDescription: 'Neurological Condition',
            areaCode: null,
            areaDescription: null,
            listSequence: 12,
            active: true,
          },
          {
            code: 'FASD',
            description: 'Foetal Alcohol Spectrum Disorder',
            categoryCode: 'NEUROLOGICAL_CONDITION',
            categoryDescription: 'Neurological Condition',
            areaCode: null,
            areaDescription: null,
            listSequence: 13,
            active: true,
          },
          {
            code: 'NEURO_OTHER',
            description: 'Other Neurological Condition',
            categoryCode: 'NEUROLOGICAL_CONDITION',
            categoryDescription: 'Neurological Condition',
            areaCode: null,
            areaDescription: null,
            listSequence: 14,
            active: true,
          },
          {
            code: 'NEURODEGEN',
            description: 'Neurodegenerative condition',
            categoryCode: 'NEURODEGENERATIVE_CONDITION',
            categoryDescription: 'Neurodegenerative condition',
            areaCode: null,
            areaDescription: null,
            listSequence: 15,
            active: true,
          },
          {
            code: 'ABI',
            description: 'Acquired Brain Injury',
            categoryCode: 'LONG_TERM_MEDICAL_CONDITION',
            categoryDescription: 'Long term Medical Condition',
            areaCode: null,
            areaDescription: null,
            listSequence: 16,
            active: true,
          },
          {
            code: 'LONG_TERM_OTHER',
            description: 'Other Long term Medical Condition',
            categoryCode: 'LONG_TERM_MEDICAL_CONDITION',
            categoryDescription: 'Long term Medical Condition',
            areaCode: null,
            areaDescription: null,
            listSequence: 17,
            active: true,
          },
          {
            code: 'OTHER',
            description: 'Other Disability &/or health condition not listed above',
            categoryCode: 'OTHER',
            categoryDescription: 'Other disabilities and health conditions',
            areaCode: null,
            areaDescription: null,
            listSequence: 18,
            active: true,
          },
        ],
      },
    },
  })

export default { stubChallengesReferenceData, stubStrengthsReferenceData, stubConditionsReferenceData }
