import StrengthType from '../enums/strengthType'

const strengthTypeScreenValues = new Map<StrengthType, string>([
  // Broad/category level Strength Types
  [StrengthType.SENSORY, 'Sensory'],
  [StrengthType.EMOTIONS_FEELINGS_DEFAULT, 'Emotions and feelings'],
  [StrengthType.PHYSICAL_SKILLS_DEFAULT, 'Physical skills and coordination'],
  [StrengthType.LITERACY_SKILLS_DEFAULT, 'Literacy skills'],
  [StrengthType.NUMERACY_SKILLS_DEFAULT, 'Numeracy skills'],
  [StrengthType.ATTENTION_ORGANISING_TIME_DEFAULT, 'Attention, organising and time management'],
  [StrengthType.LANGUAGE_COMM_SKILLS_DEFAULT, 'Language and communication skills'],
  [StrengthType.PROCESSING_SPEED, 'Processing speed'],
  [StrengthType.MEMORY, 'Memory'],

  // More specific Strength Types
  [StrengthType.HANDWRITING, 'Handwriting'],
  [StrengthType.TURN_TAKING, 'Turn-taking'],
  [StrengthType.READING, 'Reading'],
  [StrengthType.SPEED_OF_CALCULATION, 'Speed of calculation'],
  [StrengthType.RESTFULNESS, 'Restfulness'],
  [StrengthType.AUDITORY_DISCRIMINATION, 'Auditory discrimination'],
  [StrengthType.FOCUSING, 'Focusing'],
  [StrengthType.ARITHMETIC, 'Arithmetic'],
  [StrengthType.SPELLING, 'Spelling'],
  [StrengthType.READING_EMOTIONS, 'Reading emotions'],
  [StrengthType.LANGUAGE_FLUENCY, 'Language fluency'],
  [StrengthType.TIDINESS, 'Tidiness'],
  [StrengthType.BALANCE, 'Balance'],
  [StrengthType.CREATIVITY, 'Creativity'],
  [StrengthType.FINE_MOTOR_SKILLS, 'Fine motor skills'],
  [StrengthType.EMPATHY, 'Empathy'],
  [StrengthType.ESTIMATION, 'Estimation'],
  [StrengthType.WRITING, 'Writing'],
  [StrengthType.FINISHING_TASKS, 'Finishing tasks'],
  [StrengthType.SOCIAL_ADAPTABILITY, 'Social adaptability'],
  [StrengthType.LISTENING, 'Listening'],
  [StrengthType.COMMUNICATION, 'Communication'],
  [StrengthType.IMPULSE_CONTROL, 'Impulse control'],
  [StrengthType.MATHS_LITERACY, 'Maths literacy'],
  [StrengthType.LEARNING_NEW_SKILLS, 'Learning new skills'],
  [StrengthType.SENSORY_PROCESSING, 'Sensory processing'],
  [StrengthType.ALPHABET_ORDERING, 'Alphabet ordering'],
  [StrengthType.PROBLEM_SOLVING, 'Problem solving'],
  [StrengthType.TASK_INITIATION, 'Task initiation'],
  [StrengthType.EXTROVERSION_INTROVERSION, 'Extroversion/introversion'],
  [StrengthType.READING_COMPREHENSION, 'Reading comprehension'],
  [StrengthType.VISUAL_SKILLS, 'Visual skills'],
  [StrengthType.EMOTIONAL_CONTROL, 'Emotional control'],
  [StrengthType.MATHS_CONFIDENCE, 'Maths confidence'],
  [StrengthType.SPORTING_BALL_SKILLS, 'Sporting ball skills'],
  [StrengthType.VISUAL_SPATIAL_SKILLS, 'Visual-spatial skills'],
  [StrengthType.READING_VISUAL_DISCRIMINATION, 'Reading (visual discrimination)'],
  [StrengthType.FRACTIONS_PERCENTAGES, 'Fractions and percentages'],
  [StrengthType.TIME_ALLOCATION, 'Time allocation/prioritisation'],
  [StrengthType.SOCIAL_NUANCES, 'Social nuances'],
  [StrengthType.MANAGING_CHANGE, 'Managing change (adaptability)'],
  [StrengthType.DUAL_TASKING, 'Dual tasking'],
  [StrengthType.CONFIDENCE, 'Confidence'],
  [StrengthType.TRACKING, 'Tracking'],
  [StrengthType.FOLDING_PACKING_SORTING, 'Folding, packing, and sorting'],
  [StrengthType.SPEAKING, 'Speaking'],
  [StrengthType.SELF_ORGANISED, 'Self organised (routine)'],
  [StrengthType.WORD_BASED_PROBLEMS, 'Word-based problems'],
  [StrengthType.MONEY_MANAGEMENT, 'Money management'],
  [StrengthType.FORWARD_PLANNING, 'Forward planning'],
  [StrengthType.LANGUAGE_DECODING, 'Language decoding'],
  [StrengthType.WORD_FINDING, 'Word finding'],
  [StrengthType.CALM, 'Calm'],
  [StrengthType.STAMINA, 'Stamina'],
  [StrengthType.ACTIVE_LISTENING, 'Active listening'],
  [StrengthType.GRASP, 'Grasp'],
  [StrengthType.NUMBER_RECALL, 'Number recall'],
  [StrengthType.ATTENTION_TO_DETAIL, 'Attention to detail'],
  [StrengthType.SPATIAL_AWARENESS, 'Spatial awareness'],
  [StrengthType.NON_VERBAL_COMMUNICATION, 'Non-verbal communication'],
  [StrengthType.TASK_SWITCHING, 'Task switching'],
  [StrengthType.NUMBER_SEQUENCING, 'Number sequencing'],
  [StrengthType.PEOPLE_PERSON, 'People person'],
  [StrengthType.SHORT_TERM_MEMORY, 'Short term memory'],
  [StrengthType.LONG_TERM_MEMORY, 'Long term memory'],

  [StrengthType.NONE, 'No strengths identified'],
])

const strengthTypeHintTextValues = new Map<StrengthType, string>([
  [StrengthType.SENSORY, 'Things like reacting to some environments or situations eg noise or being touched'],
  [StrengthType.EMOTIONS_FEELINGS_DEFAULT, 'Things like confidence, empathy, managing emotions and impulses'],
  [
    StrengthType.PHYSICAL_SKILLS_DEFAULT,
    'Things like learning new skills, co-ordination, stamina and fine motor skills',
  ],
  [StrengthType.LITERACY_SKILLS_DEFAULT, 'Things like reading, writing and spelling'],
  [StrengthType.NUMERACY_SKILLS_DEFAULT, 'Things like maths and managing money'],
  [StrengthType.ATTENTION_ORGANISING_TIME_DEFAULT, 'Things like planning, task management, tidiness and focus'],
  [StrengthType.LANGUAGE_COMM_SKILLS_DEFAULT, 'Things like taking turns, listening and language fluency'],
  [StrengthType.PROCESSING_SPEED, 'Things like taking time to understand and follow instructions'],
  [StrengthType.MEMORY, 'Things like remembering and recalling information'],
])

const formatStrengthTypeScreenValueFilter = (value: StrengthType): string => strengthTypeScreenValues.get(value)

const formatStrengthTypeHintTextFilter = (value: StrengthType): string => strengthTypeHintTextValues.get(value)

export { formatStrengthTypeScreenValueFilter, formatStrengthTypeHintTextFilter }
