import StrengthType from '../enums/strengthType'

const strengthTypeScreenValues: Record<StrengthType, string> = {
  HANDWRITING: 'Handwriting',
  TURN_TAKING: 'Turn taking',
  READING: 'Reading',
  SPEED_OF_CALCULATION: 'Speed of calculation',
  RESTFULNESS: 'Restfulness',
  AUDITORY_DISCRIMINATION: 'Auditory discrimination',
  FOCUSING: 'Focusing',
  ARITHMETIC: 'Arithmetic',
  SPELLING: 'Spelling',
  READING_EMOTIONS: 'Reading emotions',
  LANGUAGE_FLUENCY: 'Language fluency',
  TIDINESS: 'Tidiness',
  BALANCE: 'Balance',
  CREATIVITY: 'Creativity',
  FINE_MOTOR_SKILLS: 'Fine motor skills',
  EMPATHY: 'Empathy',
  ESTIMATION: 'Estimation',
  WRITING: 'Writing',
  FINISHING_TASKS: 'Finishing tasks',
  SOCIAL_ADAPTABILITY: 'Social adaptability',
  LISTENING: 'Listening',
  COMMUNICATION: 'Communication',
  IMPULSE_CONTROL: 'Impulse control',
  MATHS_LITERACY: 'Maths literacy',
  LEARNING_NEW_SKILLS: 'Learning new skills',
  SENSORY_PROCESSING: 'Sensory processing',
  ALPHABET_ORDERING: 'Alphabet ordering',
  PROBLEM_SOLVING: 'Problem solving',
  TASK_INITIATION: 'Task initiation',
  EXTROVERSION_INTROVERSION: 'Extroversion/introversion',
  READING_COMPREHENSION: 'Reading comprehension',
  VISUAL_SKILLS: 'Visual skills',
  EMOTIONAL_CONTROL: 'Emotional control',
  MATHS_CONFIDENCE: 'Maths confidence',
  SPORTING_BALL_SKILLS: 'Sporting ball skills',
  VISUAL_SPATIAL_SKILLS: 'Visual spatial skills',
  READING_VISUAL_DISCRIMINATION: 'Reading (visual discrimination)',
  FRACTIONS_PERCENTAGES: 'Fractions and percentages',
  TIME_ALLOCATION: 'Time allocation/prioritisation',
  SOCIAL_NUANCES: 'Social nuances',
  MANAGING_CHANGE: 'Managing change (adaptability)',
  DUAL_TASKING: 'Dual tasking',
  CONFIDENCE: 'Confidence',
  TRACKING: 'Tracking',
  FOLDING_PACKING_SORTING: 'Folding, packing, and sorting',
  SPEAKING: 'Speaking',
  SELF_ORGANISED: 'Self organised (routine)',
  WORD_BASED_PROBLEMS: 'Word-based_problems',
  MONEY_MANAGEMENT: 'Money management',
  FORWARD_PLANNING: 'Forward planning',
  LANGUAGE_DECODING: 'Language decoding',
  WORD_FINDING: 'Word finding',
  CALM: 'Calm',
  STAMINA: 'Stamina',
  ACTIVE_LISTENING: 'Active listening',
  GRASP: 'Grasp',
  NUMBER_RECALL: 'Number recall',
  ATTENTION_TO_DETAIL: 'Attention to detail',
  SPATIAL_AWARENESS: 'Spatial awareness',
  NON_VERBAL_COMMUNICATION: 'Non-verbal communication',
  TASK_SWITCHING: 'Task switching',
  NUMBER_SEQUENCING: 'Number sequencing',
  PEOPLE_PERSON: 'People person',
  NONE: 'No challenges identified',
}

const formatStrengthTypeScreenValueFilter = (value: StrengthType): string => strengthTypeScreenValues[value]

export default formatStrengthTypeScreenValueFilter
