enum ApplicationAction {
  SEARCH = 'SEARCH',
  VIEW_PROFILE = 'VIEW_PROFILE',
  RECORD_EDUCATION_LEARNER_SUPPORT_PLAN = 'RECORD_EDUCATION_LEARNER_SUPPORT_PLAN',
  UPDATE_EDUCATION_LEARNER_SUPPORT_PLAN = 'UPDATE_EDUCATION_LEARNER_SUPPORT_PLAN',
  RECORD_CHALLENGES = 'RECORD_CHALLENGES',
}

export default ApplicationAction
