enum DpsRole {
  // SAN roles
  ROLE_SAN_EDITOR = 'ROLE_SAN_EDITOR',
  ROLE_SAN_EDUCATION_MANAGER = 'ROLE_SAN_EDUCATION_MANAGER',

  // DPR Reporting
  ROLE_PRISONS_REPORTING_USER = 'ROLE_PRISONS_REPORTING_USER',
}

export default DpsRole
