enum PlanCreationScheduleExemptionReason {
  EXEMPT_REFUSED_TO_ENGAGE = 'EXEMPT_REFUSED_TO_ENGAGE',
  EXEMPT_NOT_REQUIRED = 'EXEMPT_NOT_REQUIRED',
  EXEMPT_INACCURATE_IDENTIFICATION = 'EXEMPT_INACCURATE_IDENTIFICATION',
}

export default PlanCreationScheduleExemptionReason
