enum SearchSortField {
  PRISONER_NAME = 'PRISONER_NAME',
  PRISON_NUMBER = 'PRISON_NUMBER',
  CELL_LOCATION = 'CELL_LOCATION',
  RELEASE_DATE = 'RELEASE_DATE',
  DEADLINE_DATE = 'DEADLINE_DATE',
  PLAN_STATUS = 'PLAN_STATUS',
  HAS_ADDITIONAL_NEED = 'HAS_ADDITIONAL_NEED',
  IN_EDUCATION = 'IN_EDUCATION',
}

export default SearchSortField
