enum SentenceType {
  RECALL = 'RECALL',
  DEAD = 'DEAD',
  INDETERMINATE_SENTENCE = 'INDETERMINATE_SENTENCE',
  SENTENCED = 'SENTENCED',
  CONVICTED_UNSENTENCED = 'CONVICTED_UNSENTENCED',
  CIVIL_PRISONER = 'CIVIL_PRISONER',
  IMMIGRATION_DETAINEE = 'IMMIGRATION_DETAINEE',
  REMAND = 'REMAND',
  UNKNOWN = 'UNKNOWN',
  OTHER = 'OTHER',
}

export default SentenceType
